#!/usr/bin/env -S sh -c "echo >&2 \"Error: You are running this script instead of sourcing it. Make sure to use it as 'source setenv' or '. setenv', otherwise its settings won't take effect.\"; exit 1"

if [ ! -f bin/inetgpl ]; then
    echo "Error: current working directory does not look like an INET-GPL root directory"
    # no exit -- it would close the shell
else
    export INETGPL_ROOT=$(pwd)
    export PATH=$INETGPL_ROOT/bin:$PATH
fi
