#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE="make MODE=debug"

# Test if we are running on OMNeT++ 5.1 as we did not have the _dbg suffix for debug binaries on 5.1
# (this can be removed if OMNeT++ 5.1 compatibility is no longer needed)
#
OMNETPP_51=$(grep "OMNETPP_VERSION = 5.1" $(opp_configfilepath))
if [ -z $OMNETPP_51 ]; then
DBG_SUFFIX="_dbg"
else
DBG_SUFFIX=""
fi

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi

cp -pPR lib work/

opp_test gen $OPT -v $TESTFILES || exit 1

echo
(cd work; opp_makemake -f --deep -lINET$DBG_SUFFIX -lINETGPL$DBG_SUFFIX -L$INET_ROOT/src -L$INETGPL_ROOT/src -P . -I$INET_ROOT/src -I$INETGPL_ROOT/src; $MAKE) || exit 1

echo
NEDPATH=$INET_ROOT/src opp_test run $OPT -v -p work$DBG_SUFFIX $TESTFILES -a "--check-signals=false" || exit 1

echo
echo Results can be found in ./work
